# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Gems
gems:
  - jekyll-assets
  - jekyll-coffeescript

# Site settings
title: kana.tools
email: hello@kana.tools
description: > # this means to ignore newlines until "baseurl:"
  A repository of Japanese kana related tools hosted by Tofugu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kana.tools" # the base hostname & protocol for your site
twitter_username: kanatools
# github_username:  jekyll
keywords:
  - japanese
  - kana
  - kana tools

# Build settings
markdown: kramdown

collections:
  tools:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ''
      type: tools
    values:
      layout: tool

# jekyll-assets settings
assets:
  compress:
    css: default
    js: default
    # cdn: 
  assets:
    - "data-*.json"
  sources:
    - _assets/bower
    - _assets/data